version: '3.7'

services:
  frontend-prod:
    container_name: frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 8877:80
    environment:
      - DOCKER_ENV=production
