version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 4000:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=4000
    env_file:
      - ./frontend/.env.staging

  db:
    image: postgres
    env_file:
      - ./services/.env.production
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/

volumes:
  db-data:
